Repository makiraid/dockers, pull requests merged in 2020-10, with the labels that each got.

#3 add nginx webserver
  nginx/docker-compose.yml
Labels: enhancement, hacktoberfest-accepted

#4 add docker compose for gitlab ce with postgresql
  gitlab-ce/docker-compose.yml
Labels: hacktoberfest-accepted

#5 add docker compose for service grafana
  grafana/docker-compose.yml
Labels: hacktoberfest-accepted

#6 Docker SQLITE3
  sqlite3/docker-compose.yml
Labels: hacktoberfest-accepted

#7 add docker compose for mssql service
  mssql/docker-compose.yml
Labels: hacktoberfest-accepted

#8 add elk stack
  elk/docker-compose.yaml
  elk/logstash/pipeline/logstash.conf
Labels: hacktoberfest-accepted

#9 add docker compose for minio
  minio/docker-compose.yaml
Labels: hacktoberfest-accepted

#11 add docker compose for keycloak service
  keycloak/docker-compose.yml
Labels: hacktoberfest-accepted

#12 Add traefik docker compose
  traefik/docker-compose.yaml
Labels: hacktoberfest-accepted

#13 Add treafik.toml
  traefik/traefik.toml
Labels: enhancement, hacktoberfest-accepted

#14 update readme and contributing file
  CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest-accepted

#16 Add wordpress docker compose
  wordpress/docker-compose.yaml
Labels: enhancement, hacktoberfest-accepted

#19 add docker compose for rabbitmq
  rabbitmq/docker-compose.yml
Labels: enhancement, hacktoberfest-accepted

#20 Create jupyter docker-compose.yml
  jupyter/docker-compose.yml
Labels: enhancement, hacktoberfest-accepted
